Meteor.methods({
	insertarCarrito:function(carrito){
		Carrito.insert(carrito);
	},
	updateUniCarrito:function(idUsu,idProd,uniNuevas){
		Carrito.update({idUsuario:idUsu,idProducto:idProd},{$set:{unidades:uniNuevas}});
	},
	deleteArtCarrito:function(id){
		Carrito.remove(id);
	},
	deleteCarrito:function(idUsu){
		Carrito.remove({idUsuario:idUsu});
	}
});